// 格言データ（AirLink から移植・quotes_port）
//
// 【重要・著作権配慮】このファイルは**サーバー専用**。クライアントコンポーネントから
// import しないこと。import するとクライアントJSにテキスト200件が丸ごと載り、
// 未ログインでもJSチャンクを直接取得すれば読めてしまう。
// 画面へは /api/quotes（ログイン必須）経由でのみ配信する。
//
// 出典について: 移植元のデータが持つのは著者名（author）のみで、書名等の出典欄は
// 元から存在しない。著者は全件そのまま保持している（改変なし）。

export type QuoteTheme =
  | "goal"
  | "thinking"
  | "relationship"
  | "management"
  | "growth"
  | "confidence"
  | "gratitude"
  | "classic";

export type Quote = {
  id: number;
  text: string;
  author: string;
  theme: QuoteTheme;
};

export const QUOTES: readonly Quote[] = [
  { id: 1, text: "成功は成長の果実", author: "青木仁志", theme: "goal" },
  { id: 2, text: "目標達成は技術である", author: "青木仁志", theme: "goal" },
  { id: 3, text: "無計画とは失敗を計画すること", author: "青木仁志", theme: "goal" },
  { id: 4, text: "人生は選択の連続である。正しい選択は正しい目的から生まれる", author: "青木仁志", theme: "goal" },
  { id: 5, text: "目標は紙に書いた瞬間から実現に向かう", author: "青木仁志", theme: "goal" },
  { id: 6, text: "成功とは自分自身の可能性を最大限に発揮すること", author: "青木仁志", theme: "goal" },
  { id: 7, text: "夢は逃げない、逃げるのはいつも自分だ", author: "青木仁志", theme: "goal" },
  { id: 8, text: "本気の人にだけチャンスは訪れる", author: "青木仁志", theme: "goal" },
  { id: 9, text: "目標がなければ、どこにも辿り着けない", author: "青木仁志", theme: "goal" },
  { id: 10, text: "達成のプロセスにこそ人生の価値がある", author: "青木仁志", theme: "goal" },
  { id: 11, text: "明確な目標を持つ者だけが明確な結果を手にする", author: "青木仁志", theme: "goal" },
  { id: 12, text: "目標達成とは自分との約束を守り続けることである", author: "青木仁志", theme: "goal" },
  { id: 13, text: "計画なき目標は単なる願望に過ぎない", author: "青木仁志", theme: "goal" },
  { id: 14, text: "期限のない目標は目標ではない。それはただの夢だ", author: "青木仁志", theme: "goal" },
  { id: 15, text: "小さな達成の積み重ねが大きな成功を生む", author: "青木仁志", theme: "goal" },
  { id: 16, text: "目標の質が人生の質を決める", author: "青木仁志", theme: "goal" },
  { id: 17, text: "描いたビジョンの大きさが、到達点の高さを決める", author: "青木仁志", theme: "goal" },
  { id: 18, text: "毎朝目標を確認する人は、確実に目標に近づいていく", author: "青木仁志", theme: "goal" },
  { id: 19, text: "真の成功者は目標を達成した後、さらに高い目標を設定する", author: "青木仁志", theme: "goal" },
  { id: 20, text: "目的地を決めない船はどの港にも辿り着けない", author: "青木仁志", theme: "goal" },
  { id: 21, text: "思考が変われば行動が変わる、行動が変われば習慣が変わる", author: "青木仁志", theme: "thinking" },
  { id: 22, text: "習慣が変われば人生が変わる", author: "青木仁志", theme: "thinking" },
  { id: 23, text: "すべての現実は二度つくられる。まず頭の中で、次に現実の世界で", author: "青木仁志", theme: "thinking" },
  { id: 24, text: "肯定的な思考は肯定的な現実を引き寄せる", author: "青木仁志", theme: "thinking" },
  { id: 25, text: "言葉が思考をつくり、思考が人生をつくる", author: "青木仁志", theme: "thinking" },
  { id: 26, text: "問題にフォーカスすれば問題が増え、解決にフォーカスすれば道が開ける", author: "青木仁志", theme: "thinking" },
  { id: 27, text: "できない理由を探すな。できる方法を考えろ", author: "青木仁志", theme: "thinking" },
  { id: 28, text: "思い込みの壁を超えた先に真の成長がある", author: "青木仁志", theme: "thinking" },
  { id: 29, text: "過去は変えられないが、未来は今この瞬間の思考で決まる", author: "青木仁志", theme: "thinking" },
  { id: 30, text: "最大の敵は外にいるのではない。自分の中の否定的な思考だ", author: "青木仁志", theme: "thinking" },
  { id: 31, text: "意識を変えれば見える世界が変わる", author: "青木仁志", theme: "thinking" },
  { id: 32, text: "行動こそが信念の証明である", author: "青木仁志", theme: "thinking" },
  { id: 33, text: "知識は力ではない。行動に移してこそ力になる", author: "青木仁志", theme: "thinking" },
  { id: 34, text: "迷ったときは、より困難な道を選べ。そこに成長がある", author: "青木仁志", theme: "thinking" },
  { id: 35, text: "考えすぎるな、動け。動きながら考えろ", author: "青木仁志", theme: "thinking" },
  { id: 36, text: "人間関係の質が人生の質を決める", author: "青木仁志", theme: "relationship" },
  { id: 37, text: "与えることは最高の生き方である", author: "青木仁志", theme: "relationship" },
  { id: 38, text: "信頼は一日にして成らず、しかし一瞬で崩れる", author: "青木仁志", theme: "relationship" },
  { id: 39, text: "人を動かすのは理論ではなく、共感である", author: "青木仁志", theme: "relationship" },
  { id: 40, text: "相手の成功を心から願える人が、真のリーダーである", author: "青木仁志", theme: "relationship" },
  { id: 41, text: "出会いの質が人生の質を決定づける", author: "青木仁志", theme: "relationship" },
  { id: 42, text: "人は認められたとき、最も大きな力を発揮する", author: "青木仁志", theme: "relationship" },
  { id: 43, text: "聴くことは最高の愛情表現である", author: "青木仁志", theme: "relationship" },
  { id: 44, text: "他者への貢献なくして真の成功はあり得ない", author: "青木仁志", theme: "relationship" },
  { id: 45, text: "人との絆は自分から築くものである", author: "青木仁志", theme: "relationship" },
  { id: 46, text: "本物の人間関係は利害を超えたところに生まれる", author: "青木仁志", theme: "relationship" },
  { id: 47, text: "相手を変えたければ、まず自分が変わることだ", author: "青木仁志", theme: "relationship" },
  { id: 48, text: "人は自分を理解してくれる人についていく", author: "青木仁志", theme: "relationship" },
  { id: 49, text: "人を育てるとは、その人の可能性を信じ続けることである", author: "青木仁志", theme: "relationship" },
  { id: 50, text: "良い人間関係は良い質問から始まる", author: "青木仁志", theme: "relationship" },
  { id: 51, text: "理念なき経営は経営にあらず", author: "青木仁志", theme: "management" },
  { id: 52, text: "経営とは理念を実現する手段である", author: "青木仁志", theme: "management" },
  { id: 53, text: "リーダーの器以上に組織は成長しない", author: "青木仁志", theme: "management" },
  { id: 54, text: "企業の成長は社員の成長の総和である", author: "青木仁志", theme: "management" },
  { id: 55, text: "売上は社会への貢献度のバロメーターである", author: "青木仁志", theme: "management" },
  { id: 56, text: "経営者の仕事は環境をつくることである", author: "青木仁志", theme: "management" },
  { id: 57, text: "理念が浸透した組織は逆境にも強い", author: "青木仁志", theme: "management" },
  { id: 58, text: "ビジョンなき組織に人はついてこない", author: "青木仁志", theme: "management" },
  { id: 59, text: "経営の原点は人を活かすことにある", author: "青木仁志", theme: "management" },
  { id: 60, text: "社員が誇りを持てる会社こそが一流の会社である", author: "青木仁志", theme: "management" },
  { id: 61, text: "利益は目的ではなく、社会貢献の結果である", author: "青木仁志", theme: "management" },
  { id: 62, text: "理念に共感する仲間が集まったとき、組織は最強になる", author: "青木仁志", theme: "management" },
  { id: 63, text: "経営者は夢を語り、社員はその夢を共有する。それが最高のチームだ", author: "青木仁志", theme: "management" },
  { id: 64, text: "組織の力は、最も弱いメンバーをどれだけ支えられるかで決まる", author: "青木仁志", theme: "management" },
  { id: 65, text: "真のリーダーは、自分がいなくても回る組織をつくる人である", author: "青木仁志", theme: "management" },
  { id: 66, text: "成長なくして成功なし", author: "青木仁志", theme: "growth" },
  { id: 67, text: "逆境は天が与えた最高のギフトである", author: "青木仁志", theme: "growth" },
  { id: 68, text: "安定を求めた瞬間に衰退が始まる", author: "青木仁志", theme: "growth" },
  { id: 69, text: "失敗は成長のための授業料である", author: "青木仁志", theme: "growth" },
  { id: 70, text: "人は変われる。変わる決意さえあれば", author: "青木仁志", theme: "growth" },
  { id: 71, text: "学び続ける者だけが時代をリードできる", author: "青木仁志", theme: "growth" },
  { id: 72, text: "今日の自分を超えることが唯一の競争である", author: "青木仁志", theme: "growth" },
  { id: 73, text: "成長の痛みを避ける者に成功は訪れない", author: "青木仁志", theme: "growth" },
  { id: 74, text: "壁にぶつかったとき、それは次のステージへの扉である", author: "青木仁志", theme: "growth" },
  { id: 75, text: "完璧を待つな。まず動け。動きながら完璧に近づけ", author: "青木仁志", theme: "growth" },
  { id: 76, text: "インプットの質がアウトプットの質を決める", author: "青木仁志", theme: "growth" },
  { id: 77, text: "成長とは快適な領域から一歩踏み出すことである", author: "青木仁志", theme: "growth" },
  { id: 78, text: "昨日の自分と今日の自分を比べよ。他人と比べるな", author: "青木仁志", theme: "growth" },
  { id: 79, text: "苦労した分だけ、人間としての深みが増す", author: "青木仁志", theme: "growth" },
  { id: 80, text: "成長のない成功は、やがて色褪せる", author: "青木仁志", theme: "growth" },
  { id: 81, text: "自分の可能性を信じ切ることが成功の第一歩", author: "青木仁志", theme: "confidence" },
  { id: 82, text: "人は誰でも無限の可能性を持っている", author: "青木仁志", theme: "confidence" },
  { id: 83, text: "自信とは自分を信じると書く。まず自分を信じよ", author: "青木仁志", theme: "confidence" },
  { id: 84, text: "他人の評価より自分の基準で生きよ", author: "青木仁志", theme: "confidence" },
  { id: 85, text: "自分を安売りするな。あなたの価値はあなたが決める", author: "青木仁志", theme: "confidence" },
  { id: 86, text: "過去の成功体験が未来の自信をつくる", author: "青木仁志", theme: "confidence" },
  { id: 87, text: "まだ見ぬ自分に出会える喜びを知れ", author: "青木仁志", theme: "confidence" },
  { id: 88, text: "弱さを認められる人こそ本当に強い人である", author: "青木仁志", theme: "confidence" },
  { id: 89, text: "セルフイメージが人生の天井を決める", author: "青木仁志", theme: "confidence" },
  { id: 90, text: "自分を信じる力は、行動した回数に比例する", author: "青木仁志", theme: "confidence" },
  { id: 91, text: "感謝は成功の加速装置である", author: "青木仁志", theme: "gratitude" },
  { id: 92, text: "感謝できる人は、どんな状況からも学べる人である", author: "青木仁志", theme: "gratitude" },
  { id: 93, text: "ありがとうの数が人生の豊かさを決める", author: "青木仁志", theme: "gratitude" },
  { id: 94, text: "当たり前のことに感謝できる人が一流になれる", author: "青木仁志", theme: "gratitude" },
  { id: 95, text: "感謝の心が人を惹きつけ、道を開く", author: "青木仁志", theme: "gratitude" },
  { id: 96, text: "不満を数えるな。恵みを数えよ", author: "青木仁志", theme: "gratitude" },
  { id: 97, text: "感謝は最も美しい人間の姿である", author: "青木仁志", theme: "gratitude" },
  { id: 98, text: "苦しいときこそ感謝を忘れるな。そこに突破口がある", author: "青木仁志", theme: "gratitude" },
  { id: 99, text: "成功者に共通するたった一つの習慣、それは感謝である", author: "青木仁志", theme: "gratitude" },
  { id: 100, text: "今あるものに感謝できる人だけが、さらなる豊かさを受け取れる", author: "青木仁志", theme: "gratitude" },
  { id: 101, text: "豊かな人生よりも豊かな人間になることを求めなさい。何故ならば、豊かな人間こそが豊かな人生を築き上げることが出来るのだから", author: "夏目志郎", theme: "classic" },
  { id: 102, text: "千里の道も一歩から", author: "老子", theme: "classic" },
  { id: 103, text: "足るを知る者は富む", author: "老子", theme: "classic" },
  { id: 104, text: "他人を知る者は智なり、自らを知る者は明なり", author: "老子", theme: "classic" },
  { id: 105, text: "上善は水の如し。水はよく万物を利して争わず", author: "老子", theme: "classic" },
  { id: 106, text: "柔よく剛を制す", author: "老子", theme: "classic" },
  { id: 107, text: "自分が見たいと思う変化に、自分自身がなりなさい", author: "マハトマ・ガンジー", theme: "classic" },
  { id: 108, text: "明日死ぬかのように生きよ。永遠に生きるかのように学べ", author: "マハトマ・ガンジー", theme: "classic" },
  { id: 109, text: "強さとは身体的な力ではない。不屈の意志から生まれるのだ", author: "マハトマ・ガンジー", theme: "classic" },
  { id: 110, text: "許しは強さの証である。弱い者は決して許すことができない", author: "マハトマ・ガンジー", theme: "classic" },
  { id: 111, text: "行動が思想を表現するとき、最も美しい調和が生まれる", author: "マハトマ・ガンジー", theme: "classic" },
  { id: 112, text: "大切なのはどれだけ多くのことをしたかではなく、どれだけ心を込めたかです", author: "マザー・テレサ", theme: "classic" },
  { id: 113, text: "世界平和のためにできることですか？家に帰って家族を愛してあげてください", author: "マザー・テレサ", theme: "classic" },
  { id: 114, text: "愛の反対は憎しみではありません。無関心です", author: "マザー・テレサ", theme: "classic" },
  { id: 115, text: "小さなことに誠実でいなさい。そこにあなたの力が宿るのですから", author: "マザー・テレサ", theme: "classic" },
  { id: 116, text: "昨日は去りました。明日はまだ来ていません。今日だけがあるのです", author: "マザー・テレサ", theme: "classic" },
  { id: 117, text: "最も大切なことは、ただ一つ、今この瞬間を精一杯生きること", author: "松下幸之助", theme: "classic" },
  { id: 118, text: "失敗したところでやめてしまうから失敗になる。成功するまで続ければ成功になる", author: "松下幸之助", theme: "classic" },
  { id: 119, text: "素直な心になりましょう。素直な心はあなたを強く正しく聡明にします", author: "松下幸之助", theme: "classic" },
  { id: 120, text: "志を立てるのに老いも若きもない。そして志あるところ、老いも又青春である", author: "松下幸之助", theme: "classic" },
  { id: 121, text: "万策尽きたと思うな。自ら断崖に立て。その時はじめて新たなる風は必ず吹く", author: "松下幸之助", theme: "classic" },
  { id: 122, text: "人生の結果 = 考え方 × 熱意 × 能力", author: "稲盛和夫", theme: "classic" },
  { id: 123, text: "動機善なりや、私心なかりしか", author: "稲盛和夫", theme: "classic" },
  { id: 124, text: "楽観的に構想し、悲観的に計画し、楽観的に実行する", author: "稲盛和夫", theme: "classic" },
  { id: 125, text: "心に描いたものが人生をつくる。だからこそ美しい心を持つことが大切である", author: "稲盛和夫", theme: "classic" },
  { id: 126, text: "仕事を好きになりなさい。好きになれば工夫が生まれ、成果が生まれる", author: "稲盛和夫", theme: "classic" },
  { id: 127, text: "小さなことの積み重ねがとんでもないところへ行くただ一つの道", author: "イチロー", theme: "classic" },
  { id: 128, text: "準備というのは、言い訳の材料となり得るものを排除していくこと", author: "イチロー", theme: "classic" },
  { id: 129, text: "確かな一歩の積み重ねでしか遠くへは行けない", author: "イチロー", theme: "classic" },
  { id: 130, text: "夢を掴むことは一気にはできない。小さなことを積み重ねることで、いつの日か信じられないような力を出せるようになる", author: "イチロー", theme: "classic" },
  { id: 131, text: "特別なことをするために特別なことをするのではない。特別なことをするために普段通りの当たり前のことをする", author: "イチロー", theme: "classic" },
  { id: 132, text: "憧れるのをやめましょう。憧れてしまったら超えられないから", author: "大谷翔平", theme: "classic" },
  { id: 133, text: "目の前のことに全力を尽くす。それが一番の近道だと思う", author: "大谷翔平", theme: "classic" },
  { id: 134, text: "自分の限界はまだまだ先にあると思っている", author: "大谷翔平", theme: "classic" },
  { id: 135, text: "ハングリーであれ、愚かであれ", author: "スティーブ・ジョブズ", theme: "classic" },
  { id: 136, text: "点と点がつながると信じなさい。その信念が道を切り開く", author: "スティーブ・ジョブズ", theme: "classic" },
  { id: 137, text: "あなたの時間は限られている。他人の人生を生きて時間を無駄にしてはいけない", author: "スティーブ・ジョブズ", theme: "classic" },
  { id: 138, text: "素晴らしい仕事をする唯一の方法は、自分の仕事を愛することだ", author: "スティーブ・ジョブズ", theme: "classic" },
  { id: 139, text: "イノベーションとはリーダーとフォロワーの違いを生むものだ", author: "スティーブ・ジョブズ", theme: "classic" },
  { id: 140, text: "思考は現実化する。心の中で想像できるものは必ず実現できる", author: "ナポレオン・ヒル", theme: "classic" },
  { id: 141, text: "どんな逆境の中にも、それと同等かそれ以上の恩恵の種子が含まれている", author: "ナポレオン・ヒル", theme: "classic" },
  { id: 142, text: "目標とは期限付きの夢のことである", author: "ナポレオン・ヒル", theme: "classic" },
  { id: 143, text: "成功は求めてやってくるものではなく、引き寄せるものである", author: "ナポレオン・ヒル", theme: "classic" },
  { id: 144, text: "人間の心が想像し、信じることができるものは、必ず達成できる", author: "ナポレオン・ヒル", theme: "classic" },
  { id: 145, text: "人の名前はその人にとって最も心地よい音である", author: "デール・カーネギー", theme: "classic" },
  { id: 146, text: "他人を批判する代わりに、理解するよう努めよう", author: "デール・カーネギー", theme: "classic" },
  { id: 147, text: "人を動かす秘訣は、自ら動きたくなる気持ちを起こさせることだ", author: "デール・カーネギー", theme: "classic" },
  { id: 148, text: "成功に秘訣というものがあるとすれば、他人の立場を理解する能力である", author: "デール・カーネギー", theme: "classic" },
  { id: 149, text: "心からの賞賛と惜しみない称賛を与えよ", author: "デール・カーネギー", theme: "classic" },
  { id: 150, text: "重要事項を優先せよ。緊急ではないが重要なことに時間を使え", author: "スティーブン・コヴィー", theme: "classic" },
  { id: 151, text: "インサイド・アウト。自分自身の内面から変えていくことが全ての始まりである", author: "スティーブン・コヴィー", theme: "classic" },
  { id: 152, text: "理解してから理解される。まず相手を理解するよう努めよ", author: "スティーブン・コヴィー", theme: "classic" },
  { id: 153, text: "主体的であれ。反応的な人生ではなく、自ら選択する人生を生きよ", author: "スティーブン・コヴィー", theme: "classic" },
  { id: 154, text: "Win-Winを考えよ。勝利は分かち合えるものだ", author: "スティーブン・コヴィー", theme: "classic" },
  { id: 155, text: "未来を予測する最良の方法は、それを自ら創造することだ", author: "ピーター・ドラッカー", theme: "classic" },
  { id: 156, text: "マネジメントとは人に関わることである。その目的は人の強みを生産的にすることだ", author: "ピーター・ドラッカー", theme: "classic" },
  { id: 157, text: "成果をあげる人は仕事からスタートしない。時間からスタートする", author: "ピーター・ドラッカー", theme: "classic" },
  { id: 158, text: "効率とは物事を正しく行うことであり、効果とは正しい物事を行うことである", author: "ピーター・ドラッカー", theme: "classic" },
  { id: 159, text: "自らの強みに集中せよ。弱みで何かを成し遂げることはできない", author: "ピーター・ドラッカー", theme: "classic" },
  { id: 160, text: "困難の中にこそ機会がある", author: "アインシュタイン", theme: "classic" },
  { id: 161, text: "想像力は知識より重要である。知識には限界があるが、想像力は世界を包み込む", author: "アインシュタイン", theme: "classic" },
  { id: 162, text: "同じことを繰り返しながら違う結果を期待するのは狂気である", author: "アインシュタイン", theme: "classic" },
  { id: 163, text: "人生には二つの生き方がある。奇跡など何もないと思って生きるか、すべてが奇跡だと思って生きるかだ", author: "アインシュタイン", theme: "classic" },
  { id: 164, text: "自分自身を信じた瞬間、どう生きるかが見えてくる", author: "ゲーテ", theme: "classic" },
  { id: 165, text: "人間の最大の罪は不機嫌である", author: "ゲーテ", theme: "classic" },
  { id: 166, text: "涙とともにパンを食べたものでなければ、人生の味はわからない", author: "ゲーテ", theme: "classic" },
  { id: 167, text: "挑戦しなければ、変わることはできない", author: "本田宗一郎", theme: "classic" },
  { id: 168, text: "成功は99%の失敗に支えられた1%だ", author: "本田宗一郎", theme: "classic" },
  { id: 169, text: "人を動かすことのできる人は、他人の気持ちになれる人である", author: "本田宗一郎", theme: "classic" },
  { id: 170, text: "夢を見ることができれば、それは実現できる", author: "ウォルト・ディズニー", theme: "classic" },
  { id: 171, text: "前に進み続けることだ。そうすれば新しい扉が開く", author: "ウォルト・ディズニー", theme: "classic" },
  { id: 172, text: "夢をかなえる秘訣は、四つのCに集約される。好奇心、自信、勇気、そして継続だ", author: "ウォルト・ディズニー", theme: "classic" },
  { id: 173, text: "成功とは情熱を失わずに失敗から失敗へ進む能力のことである", author: "チャーチル", theme: "classic" },
  { id: 174, text: "悲観主義者はあらゆる機会の中に困難を見出す。楽観主義者はあらゆる困難の中に機会を見出す", author: "チャーチル", theme: "classic" },
  { id: 175, text: "決して、決して、決して諦めるな", author: "チャーチル", theme: "classic" },
  { id: 176, text: "準備しておこう。チャンスはいつか訪れるものだ", author: "リンカーン", theme: "classic" },
  { id: 177, text: "木を切り倒すのに六時間もらえるなら、最初の四時間は斧を研ぐことに使う", author: "リンカーン", theme: "classic" },
  { id: 178, text: "私の歩みは遅いが、歩んだ道を引き返すことはない", author: "リンカーン", theme: "classic" },
  { id: 179, text: "天才とは1%のひらめきと99%の努力である", author: "エジソン", theme: "classic" },
  { id: 180, text: "私は失敗したことがない。うまくいかない一万通りの方法を発見しただけだ", author: "エジソン", theme: "classic" },
  { id: 181, text: "多くの人が機会を逃すのは、それが作業服を着て仕事のように見えるからだ", author: "エジソン", theme: "classic" },
  { id: 182, text: "天は人の上に人を造らず、人の下に人を造らず", author: "福沢諭吉", theme: "classic" },
  { id: 183, text: "学問の本質は読書にあらず、精神の働きにあり", author: "福沢諭吉", theme: "classic" },
  { id: 184, text: "たった一人で見る夢はただの夢。みんなで見る夢は現実になる", author: "ヘレン・ケラー", theme: "classic" },
  { id: 185, text: "人生は大胆な冒険か、それとも何もないかのどちらかです", author: "ヘレン・ケラー", theme: "classic" },
  { id: 186, text: "世界で最も良いもの、最も美しいものは目に見えず触れることもできない。心で感じなければならないのです", author: "ヘレン・ケラー", theme: "classic" },
  { id: 187, text: "今日できることを明日に延ばすな", author: "ベンジャミン・フランクリン", theme: "classic" },
  { id: 188, text: "投資の中で最も利回りが高いのは、知識への投資である", author: "ベンジャミン・フランクリン", theme: "classic" },
  { id: 189, text: "一日一日を大切にせよ。毎日のわずかな差が人生を決める", author: "野村克也", theme: "classic" },
  { id: 190, text: "失敗と書いて成長と読む", author: "野村克也", theme: "classic" },
  { id: 191, text: "過ちて改めざる、是を過ちという", author: "孔子", theme: "classic" },
  { id: 192, text: "学びて思わざれば則ち罔し。思いて学ばざれば則ち殆し", author: "孔子", theme: "classic" },
  { id: 193, text: "己の欲せざるところ、人に施すことなかれ", author: "孔子", theme: "classic" },
  { id: 194, text: "誰もが世界を変えたいと思うが、誰も自分自身を変えようとは思わない", author: "トルストイ", theme: "classic" },
  { id: 195, text: "幸せな家庭はどれも似通っているが、不幸な家庭はそれぞれ違った形で不幸である", author: "トルストイ", theme: "classic" },
  { id: 196, text: "夢なき者に理想なし、理想なき者に計画なし、計画なき者に実行なし", author: "渋沢栄一", theme: "classic" },
  { id: 197, text: "論語と算盤は一致すべきものである。道徳と経済は共に歩むべきものだ", author: "渋沢栄一", theme: "classic" },
  { id: 198, text: "為せば成る、為さねば成らぬ何事も。成らぬは人の為さぬなりけり", author: "上杉鷹山", theme: "classic" },
  { id: 199, text: "人に勝つより自分に勝て", author: "嘉納治五郎", theme: "classic" },
  { id: 200, text: "人生とは自分を見つけることではない。自分を創ることである", author: "バーナード・ショー", theme: "classic" },
];
